version: "3.8"

services:
  aqua-core:
    build: .
    container_name: aqua-core-app
    ports:
      - "80:80"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - mlops_network

networks:
  mlops_network:
